// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeSoYzJZuXyXMYJ-Koud2MHnAl8Xs_FWI',
    appId: '1:239125281431:web:89a30cd2b7bf55a80407d2',
    messagingSenderId: '239125281431',
    projectId: 'volley-manager-f3cff',
    authDomain: 'volley-manager-f3cff.firebaseapp.com',
    storageBucket: 'volley-manager-f3cff.firebasestorage.app',
    measurementId: 'G-5PYWWLD9YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZ7JVbzq3rMtm60UrD2el6aBSGPHO8T4',
    appId: '1:239125281431:android:453ea686c97f68c90407d2',
    messagingSenderId: '239125281431',
    projectId: 'volley-manager-f3cff',
    storageBucket: 'volley-manager-f3cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DIE3YG5yHDUau-UbsU0qSdVD6P9_GKs',
    appId: '1:239125281431:ios:470758954fe425420407d2',
    messagingSenderId: '239125281431',
    projectId: 'volley-manager-f3cff',
    storageBucket: 'volley-manager-f3cff.firebasestorage.app',
    androidClientId: '239125281431-ch5d7m52eogkvp7vo6rksfgbe3tc5nf5.apps.googleusercontent.com',
    iosClientId: '239125281431-tvrs9d54srg36a4ra6ck0tnti2ajomkv.apps.googleusercontent.com',
    iosBundleId: 'com.rafal.volleymanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DIE3YG5yHDUau-UbsU0qSdVD6P9_GKs',
    appId: '1:239125281431:ios:470758954fe425420407d2',
    messagingSenderId: '239125281431',
    projectId: 'volley-manager-f3cff',
    storageBucket: 'volley-manager-f3cff.firebasestorage.app',
    iosBundleId: 'com.rafal.volleymanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeSoYzJZuXyXMYJ-Koud2MHnAl8Xs_FWI',
    appId: '1:239125281431:web:90521000392562540407d2',
    messagingSenderId: '239125281431',
    projectId: 'volley-manager-f3cff',
    authDomain: 'volley-manager-f3cff.firebaseapp.com',
    storageBucket: 'volley-manager-f3cff.firebasestorage.app',
    measurementId: 'G-DCR2JH36WW',
  );
}